import type { BapsSnapshot } from "./types";

/** Dados de primeira apresentação (espelham supabase/schema.sql). Usados quando não há Supabase ou tabela vazia. */
export const BAPS_DEFAULT_SNAPSHOT: BapsSnapshot = {
  financeiro_resumo: {
    id: 1,
    saldo_global: 1_190_000,
    deficit_q1: -25_900,
    contas_bancarias:
      "Contas operacionais consolidadas sob revisão da diretoria.",
    pendencias:
      "Conciliações de cartão e notas de terceiros em fechamento mensal.",
    inadimplencia_patrocinadores:
      "Acompanhamento amigável com cartas de cobrança padronizadas.",
    referencia_mes: "mar/2026",
  },
  financeiro_eventos: [
    {
      id: "seed-ev-summit",
      nome_evento: "Summit Turismo Saúde",
      cidade: "Goiânia",
      receitas: 82_590,
      despesas_pagas: 106_102,
      referencia: "Mar/2026 · resultado controlado na diretoria",
    },
  ],
  associados_resumo: {
    id: 1,
    total_ativos: 428,
    vencimentos_mes: 36,
    saidas_mes: 5,
    saidas_semana: 2,
    saidas_ytd: 18,
    notas_comercial:
      "Alinhar contratos com cenografia e métricas de engajamento no estande; definir SLAs claros para entrega de leads qualificados ao comercial após cada evento.",
  },
  institucional: {
    id: 1,
    atas_procuracoes_ok: true,
    status_estatutario: "Regular · sem pendências cadastrais na Junta.",
    proxima_assembleia: "2026-06-18",
    regimento_interno_ok: true,
  },
  evento_trilhas: [
    {
      id: "seed-tr-face",
      slug: "face",
      nome: "Face",
      status: "success",
      detalhe: "Palestrantes Bravo/Kassir confirmados.",
      palestrantes: "Francisco Bravo · Ramtin Kassir",
      ordem: 1,
    },
    {
      id: "seed-tr-mama",
      slug: "mama",
      nome: "Mama",
      status: "warning",
      detalhe: "Aguardando 9 convites nacionais.",
      palestrantes:
        "Ernesto Buccheri · Francisco Bravo · Reynaldo Llamas",
      ordem: 2,
    },
    {
      id: "seed-tr-corporal",
      slug: "corporal",
      nome: "Corporal",
      status: "critical",
      detalhe: "Atraso crítico; 6 internacionais sem convite.",
      palestrantes: "Equipe produção · revisão diretoria",
      ordem: 3,
    },
    {
      id: "seed-tr-prepos",
      slug: "pre-pos",
      nome: "Pré e Pós",
      status: "warning",
      detalhe:
        "Estrutura pronta; pendências administrativas em fechamento.",
      palestrantes: "Coordenação acadêmica · secretaria",
      ordem: 4,
    },
    {
      id: "seed-tr-gestao",
      slug: "gestao",
      nome: "Gestão",
      status: "critical",
      detalhe: "Sem entregas iniciais.",
      palestrantes: "PMO · operações",
      ordem: 5,
    },
  ],
  nps_metricas: [
    { id: "seed-nps-d24", categoria: "Doctors", ano: 2024, valor: 34 },
    { id: "seed-nps-d25", categoria: "Doctors", ano: 2025, valor: 54 },
    { id: "seed-nps-pp24", categoria: "Pré/Pós", ano: 2024, valor: 39 },
    { id: "seed-nps-pp25", categoria: "Pré/Pós", ano: 2025, valor: 71 },
    { id: "seed-nps-g24", categoria: "Gestores", ano: 2024, valor: 42 },
    { id: "seed-nps-g25", categoria: "Gestores", ano: 2025, valor: 65 },
  ],
  contratos: [
    {
      id: "seed-c-salvador",
      fornecedor: "Salvador · operação logística premium",
      status: "gestao_assinaturas",
      data_inicio: "2026-02-10",
      emissao_nf: null,
      vencimento_tipo: "15_dias",
      vencimento_data: "2026-03-15",
      responsavel: "Diretoria Jurídica",
      testemunha_andressa: true,
      testemunha_ana_paula: false,
      decisao_notas:
        "Decisão: minuta não habitual aprovada com cláusulas de SLA e multa simétrica; envio para assinatura física na segunda rodada.",
      destaque_risco: true,
    },
    {
      id: "seed-c-noronha",
      fornecedor: "Fornecedor de Cabeças de Noronha",
      status: "em_elaboracao",
      data_inicio: "2026-01-05",
      emissao_nf: null,
      vencimento_tipo: "automatico",
      vencimento_data: null,
      responsavel: "Procuradoria interna",
      testemunha_andressa: true,
      testemunha_ana_paula: true,
      decisao_notas:
        "Decisão: contingenciamento de pagamentos até homologação final do escopo; parecer externo arquivado junto ao dossiê.",
      destaque_risco: true,
    },
    {
      id: "seed-c-audio",
      fornecedor: "Audiovisual institucional",
      status: "demanda",
      data_inicio: "2026-03-01",
      emissao_nf: null,
      vencimento_tipo: "15_dias",
      vencimento_data: null,
      responsavel: "Marketing",
      testemunha_andressa: false,
      testemunha_ana_paula: false,
      decisao_notas: null,
      destaque_risco: false,
    },
    {
      id: "seed-c-cloud",
      fornecedor: "Infraestrutura cloud corporativa",
      status: "ativo",
      data_inicio: "2025-08-01",
      emissao_nf: "2025-08-05",
      vencimento_tipo: "automatico",
      vencimento_data: "2026-08-01",
      responsavel: "TI",
      testemunha_andressa: false,
      testemunha_ana_paula: true,
      decisao_notas: null,
      destaque_risco: false,
    },
  ],
  processos: [
    {
      id: "seed-p1",
      tipo: "judicial",
      parte_envolvida: "Cenografia Brasil Ltda.",
      numero: "0001234-56.2025.8.26.0100",
      tribunal: "TJSP · 5ª Vara Cível",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Contestação protocolada; aguardando audiência de conciliação.",
      nivel_risco: "medio",
    },
    {
      id: "seed-p2",
      tipo: "extrajudicial",
      parte_envolvida: "TGMED Serviços",
      numero: "EXT-2025-089",
      tribunal: "—",
      fase: "inicial",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Notificação extrajudicial enviada; prazo 15 dias.",
      nivel_risco: "baixo",
    },
    {
      id: "seed-p3",
      tipo: "judicial",
      parte_envolvida: "Mtech Indústria",
      numero: "0008877-11.2024.8.05.0001",
      tribunal: "TJBA · Comercial",
      fase: "julgado",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Sentença publicada; análise de recurso.",
      nivel_risco: "alto",
    },
    {
      id: "seed-p4",
      tipo: "extrajudicial",
      parte_envolvida: "Sucesso Médico Editora",
      numero: "EXT-2026-014",
      tribunal: "—",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal: "Proposta de acordo em revisão.",
      nivel_risco: "medio",
    },
    {
      id: "seed-p5",
      tipo: "judicial",
      parte_envolvida: "Ammare Holding",
      numero: "0005512-33.2025.8.13.0024",
      tribunal: "TJMG · Fazenda",
      fase: "inicial",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Distribuição confirmada; citação pendente.",
      nivel_risco: "alto",
    },
    {
      id: "seed-p6",
      tipo: "extrajudicial",
      parte_envolvida: "App Delivery Partners",
      numero: "EXT-2026-031",
      tribunal: "—",
      fase: "finalizado",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal: "Acordo homologado e quitado.",
      nivel_risco: "baixo",
    },
    {
      id: "seed-p7",
      tipo: "judicial",
      parte_envolvida: "Internet Fiber Co.",
      numero: "0009988-22.2023.8.26.0100",
      tribunal: "TJSP · 12ª Vara",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal: "Perícia técnica designada.",
      nivel_risco: "medio",
    },
    {
      id: "seed-p8",
      tipo: "judicial",
      parte_envolvida: "Correios · contrato histórico",
      numero: "0004421-88.2022.4.03.6100",
      tribunal: "TRF3",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Aguardando manifestação da autarquia.",
      nivel_risco: "medio",
    },
    {
      id: "seed-p9",
      tipo: "judicial",
      parte_envolvida: "Uber Brasil",
      numero: "0007744-55.2025.8.26.0100",
      tribunal: "TJSP · Cível",
      fase: "inicial",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal: "Audiência inicial marcada.",
      nivel_risco: "baixo",
    },
    {
      id: "seed-p10",
      tipo: "judicial",
      parte_envolvida: "Fast Limpeza Facilities",
      numero: "0003322-77.2026.8.26.0100",
      tribunal: "TJSP · Vara do Trabalho",
      fase: "inicial",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal: "Reunião com RH na quinta-feira.",
      nivel_risco: "alto",
    },
    {
      id: "seed-p11",
      tipo: "extrajudicial",
      parte_envolvida: "Neo Capital",
      numero: "EXT-2026-052",
      tribunal: "—",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Due diligence documental em curso.",
      nivel_risco: "medio",
    },
    {
      id: "seed-p12",
      tipo: "judicial",
      parte_envolvida: "Héctor Duran · quota societária",
      numero: "0006611-44.2025.8.26.0100",
      tribunal: "TJSP · Empresarial",
      fase: "andamento",
      responsavel_escritorio: "Escritório Meyer",
      atualizacao_semanal:
        "Audiência de instrução agendada.",
      nivel_risco: "alto",
    },
  ],
  certidoes: [
    {
      id: "seed-cert-1",
      nome: "Certidão negativa de débitos federais",
      data_ultima_emissao: "2025-11-12",
      previsao_proxima: "2026-05-12",
      status_pendencia: "Sem pendências",
    },
    {
      id: "seed-cert-2",
      nome: "Certidão estadual FGTS",
      data_ultima_emissao: "2025-10-02",
      previsao_proxima: "2026-04-02",
      status_pendencia: "Renovar antes do próximo board",
    },
    {
      id: "seed-cert-3",
      nome: "Certidão municipal ISS",
      data_ultima_emissao: "2025-12-20",
      previsao_proxima: "2026-06-15",
      status_pendencia: "Aguardando protocolo eletrônico",
    },
  ],
};
