import type { BapsSnapshot } from "./types";

/** Estado inicial vazio — sem dados demo. Todos os campos partem de zero até preenchimento real. */
export const BAPS_DEFAULT_SNAPSHOT: BapsSnapshot = {
  financeiro_resumo: {
    id: 1,
    saldo_global: 0,
    deficit_q1: 0,
    contas_bancarias: "",
    pendencias: "",
    inadimplencia_patrocinadores: "",
    referencia_mes: "",
  },
  financeiro_eventos: [],
  associados_resumo: {
    id: 1,
    total_ativos: 0,
    vencimentos_mes: 0,
    saidas_mes: 0,
    saidas_semana: 0,
    saidas_ytd: 0,
    notas_comercial: "",
  },
  institucional: {
    id: 1,
    atas_procuracoes_ok: false,
    status_estatutario: "",
    proxima_assembleia: null,
    regimento_interno_ok: false,
  },
  evento_trilhas: [],
  nps_metricas: [],
  congresso_disponibilidade: {
    id: 1,
    referencia: "",
    congressistas_cp: 0,
    residentes: 0,
    gestores: 0,
    pre_pos: 0,
    videomakers: 0,
    staffs: 0,
    staffs_patrocinio: 0,
    visitantes: 0,
    lab_face: 0,
    lab_corporal: 0,
    baps_in_the_house: 0,
    inscritos_total: 0,
    congressistas_pagantes: 0,
    congressistas_isentos: 0,
    pal_face_isentos: 0,
    pal_face_pagantes: 0,
    pal_mama_isentos: 0,
    pal_mama_pagantes: 0,
    pal_corporal_isentos: 0,
    pal_corporal_pagantes: 0,
    pal_gestao_isentos: 0,
    pal_gestao_pagantes: 0,
    pal_prepos_isentos: 0,
    pal_prepos_pagantes: 0,
  },
  contratos: [],
  processos: [],
  certidoes: [],
};
